### ISSUE TITLE
Support for Celluloid::IO

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jasonkarns/net-ssh-telnet#2]
I've been using this gem with Celluloid::IO and Net::SSH session under the hood. Since the Celluloid::IO TCPSocket injection is supported, it's all supposed to work quite well. Just there is a small feature which will break Celluloid::IO, which is the "Waittime" option: 

https://github.com/jasonkarns/net-ssh-telnet/blob/master/lib/net/ssh/telnet.rb#L353

As you see in this line (which was copied from the 1.9.3 implementation, so not necessarily your bug), the waittime activation is done through a direct IO::select call. This is a typical blocking call. If you are using some kind of reactor pattern/event loop implementation (even EventMachine), this call blocks the whole reactor. And the same happens with Celluloid::IO, which implements its own reactor. 

A Celluloid::IO telnet port has been suggested through a (currently unaccepted/closed) pull request, which I link below. they manage to workaround this issue and provide support to both blocking and non-blocking select calls (sadly, the standard library hasn't caught up yet). 

to see the workaround used for the port of net::telnet for Celluloid::IO : 
https://github.com/pberndt/celluloid-io/commit/73060d15f175b1c773606c22ea155be91dc88c99

could one provide such a workaround for net-ssh-telnet? Because currently, I have to refrain from using the Waittime option.

**Comment by jasonkarns** [comment]
I apologize for leaving this PR unattended. :/

I am not the author of this gem (nor even a maintainer). This was forked from the rubyforge git repo for my own branching purposes. However, I don't intend to maintain the gem itself or commit anything to master.
